export const RESOURCE_LIST_REQUEST = 'RESOURCE_LIST_REQUEST'; 
export const RESOURCE_LIST_SUCCESS = 'RESOURCE_LIST_SUCCESS';
export const RESOURCE_LIST_FAIL = 'RESOURCE_LIST_FAIL';

export const RESOURCE_SEARCH_LIST_REQUEST = 'RESOURCE_SEARCH_LIST_REQUEST'; 
export const RESOURCE_SEARCH_LIST_SUCCESS = 'RESOURCE_SEARCH_LIST_SUCCESS';
export const RESOURCE_SEARCH_LIST_FAIL = 'RESOURCE_SEARCH_LIST_FAIL';

export const RESOURCE_PURCHASED_LIST_REQUEST = 'RESOURCE_PURCHASED_LIST_REQUEST'; 
export const RESOURCE_PURCHASED_LIST_SUCCESS = 'RESOURCE_PURCHASED_LIST_SUCCESS';
export const RESOURCE_PURCHASED_LIST_FAIL = 'RESOURCE_PURCHASED_LIST_FAIL';

export const RESOURCE_DETAILS_REQUEST = 'RESOURCE_DETAILS_REQUEST'; 
export const RESOURCE_DETAILS_SUCCESS = 'RESOURCE_DETAILS_SUCCESS';
export const RESOURCE_DETAILS_FAIL = 'RESOURCE_DETAILS_FAIL';

export const RESOURCE_CREATE_REQUEST = 'RESOURCE_CREATE_REQUEST'; 
export const RESOURCE_CREATE_SUCCESS = 'RESOURCE_CREATE_SUCCESS';
export const RESOURCE_CREATE_FAIL = 'RESOURCE_CREATE_FAIL';

export const RESOURCE_UPDATE_REQUEST = 'RESOURCE_UPDATE_REQUEST'; 
export const RESOURCE_UPDATE_SUCCESS = 'RESOURCE_UPDATE_SUCCESS';
export const RESOURCE_UPDATE_FAIL = 'RESOURCE_UPDATE_FAIL';

export const RESOURCE_PERCENTAGE_REQUEST = 'RESOURCE_PERCENTAGE_REQUEST'; 
export const RESOURCE_PERCENTAGE_SET = 'RESOURCE_PERCENTAGE_SET';
export const RESOURCE_PERCENTAGE_FAIL = 'RESOURCE_PERCENTAGE_FAIL';