export const TEST_LIST_REQUEST = 'TEST_LIST_REQUEST'; 
export const TEST_LIST_SUCCESS = 'TEST_LIST_SUCCESS';
export const TEST_LIST_FAIL = 'TEST_LIST_FAIL';

export const TEST_DETAILS_REQUEST = 'TEST_DETAILS_REQUEST'; 
export const TEST_DETAILS_SUCCESS = 'TEST_DETAILS_SUCCESS';
export const TEST_DETAILS_FAIL = 'TEST_DETAILS_FAIL';

export const TEST_CREATE_REQUEST = 'TEST_CREATE_REQUEST'; 
export const TEST_CREATE_SUCCESS = 'TEST_CREATE_SUCCESS';
export const TEST_CREATE_FAIL = 'TEST_CREATE_FAIL';

export const TEST_UPDATE_REQUEST = 'TEST_CREATE_REQUEST'; 
export const TEST_UPDATE_SUCCESS = 'TEST_CREATE_SUCCESS';
export const TEST_UPDATE_FAIL = 'TEST_CREATE_FAIL';


export const VIDEO_PERCENTAGE_SET = 'VIDEO_PERCENTAGE_SET';