export const PLAYLIST_LIST_REQUEST = 'PLAYLIST_LIST_REQUEST'; 
export const PLAYLIST_LIST_SUCCESS = 'PLAYLIST_LIST_SUCCESS';
export const PLAYLIST_LIST_FAIL = 'PLAYLIST_LIST_FAIL';

export const PLAYLIST_DETAILS_REQUEST = 'PLAYLIST_DETAILS_REQUEST'; 
export const PLAYLIST_DETAILS_SUCCESS = 'PLAYLIST_DETAILS_SUCCESS';
export const PLAYLIST_DETAILS_FAIL = 'PLAYLIST_DETAILS_FAIL';

export const PLAYLIST_CREATE_REQUEST = 'PLAYLIST_CREATE_REQUEST'; 
export const PLAYLIST_CREATE_SUCCESS = 'PLAYLIST_CREATE_SUCCESS';
export const PLAYLIST_CREATE_FAIL = 'PLAYLIST_CREATE_FAIL';

export const PLAYLIST_UPDATE_REQUEST = 'PLAYLIST_UPDATE_REQUEST'; 
export const PLAYLIST_UPDATE_SUCCESS = 'PLAYLIST_UPDATE_SUCCESS';
export const PLAYLIST_UPDATE_FAIL = 'PLAYLIST_UPDATE_FAIL';